/* ============================================================
   app.js — filter, sort, render, refresh
   ------------------------------------------------------------
   Load order: data.js defines window.SEED, then this file.
   On an http origin the app fetches data.json and polls it on
   an interval; opened from the file system it falls back to
   the seed array so nothing breaks on a double-click.
   ============================================================ */

const REGION        = window.SEED.REGION;
const EXCHANGE_NAME = window.SEED.EXCHANGE_NAME;
const DOMAINS       = window.SEED.DOMAINS;

let DATA = [];

/* Live/historical/needs-subscription is an exchange-level fact from the
   payload (which agent sources are currently enabled), not something
   derived from any individual row — a source can come back empty on a
   given run without losing its "live" capability. */
let LIVE_EXCHANGES = new Set(window.SEED.LIVE_EXCHANGES || []);
let CURATED_NOTES  = new Map((window.SEED.CURATED_ONLY || []).map(c => [c.exchange, c.note]));

function applyExchangeStatus(payload){
  LIVE_EXCHANGES = new Set(payload.liveExchanges || window.SEED.LIVE_EXCHANGES || []);
  CURATED_NOTES  = new Map((payload.curatedOnly || window.SEED.CURATED_ONLY || []).map(c => [c.exchange, c.note]));
}

/* Attach the IR fallback route. Where a filing does not name a
   CFO, the drawer offers the company IR mailbox rather than
   naming a person the source does not name. */
function hydrate(rows){
  rows.forEach(r => { r.ir = DOMAINS[r.company] ? 'ir@' + DOMAINS[r.company] : 'N/A'; });
  return rows;
}

/* ============================================================
   REFRESH
   data.json is regenerated by .github/workflows/refresh.yml.
   The page polls it, re-renders only when the payload changes,
   and keeps whatever filters the user has set.
   ============================================================ */
const REFRESH_MS = 5 * 60 * 1000;
let lastHash = '';
let lastSync = null;

function hash(s){
  let h = 0;
  for (let i = 0; i < s.length; i++){ h = (h * 31 + s.charCodeAt(i)) | 0; }
  return String(h);
}

async function loadData(isPoll){
  if (location.protocol === 'file:'){
    DATA = hydrate(window.SEED.DATA);
    lastSync = new Date();
    return true;
  }
  try {
    const res = await fetch('data.json?t=' + Date.now(), { cache:'no-store' });
    if (!res.ok) throw new Error(res.status);
    const text = await res.text();
    const h = hash(text);
    lastSync = new Date();
    if (isPoll && h === lastHash) return false;   // unchanged, leave the view alone
    lastHash = h;
    const payload = JSON.parse(text);
    DATA = hydrate(Array.isArray(payload) ? payload : payload.listings);
    if (!Array.isArray(payload)) applyExchangeStatus(payload);
    return true;
  } catch (e) {
    if (!DATA.length){ DATA = hydrate(window.SEED.DATA); lastSync = new Date(); return true; }
    return false;                                  // keep the last good payload on a failed poll
  }
}

function stampSync(){
  const el = document.getElementById('sync');
  if (!el || !lastSync) return;
  el.textContent = 'Synced ' + lastSync.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
}

async function refresh(isPoll){
  const btn = document.getElementById('refreshBtn');
  btn?.classList.add('spin');
  const changed = await loadData(isPoll);
  btn?.classList.remove('spin');
  stampSync();
  if (changed){
    renderStats(); renderControls(); renderRail(); render();
    if (isPoll) toast('Listings updated');
  } else if (!isPoll){
    toast('Already up to date');
  }
}

/* ============================================================
   2. STATE + STORAGE
   localStorage is wrapped: it works on the deployed site and
   falls back to memory in sandboxed preview frames.
   ============================================================ */
const store = (() => {
  let mem = {};
  let ok = true;
  try { const k='__t'; localStorage.setItem(k,'1'); localStorage.removeItem(k); }
  catch(e){ ok = false; }
  return {
    get(k){ try { return ok ? localStorage.getItem(k) : mem[k] ?? null; } catch(e){ return mem[k] ?? null; } },
    set(k,v){ try { ok ? localStorage.setItem(k,v) : (mem[k]=v); } catch(e){ mem[k]=v; } }
  };
})();

let watch = new Set(JSON.parse(store.get('ipo.watchlist') || '[]'));
const state = { q:'', exchange:'', sector:'', status:'', month:'', watchOnly:false, sort:'listDate', dir:1, open:new Set() };
// A third click on the active column heading returns state.sort to null —
// a genuine unsorted state (natural load order, already date-ascending
// since that's how data.json is written) distinct from either direction,
// rather than just toggling asc/desc forever with no way back.

const $ = s => document.querySelector(s);
const NA = v => (!v || v === 'N/A');

/* ============================================================
   3. HELPERS
   ============================================================ */
function fmtDate(iso){
  const d = new Date(iso + 'T00:00:00');
  return d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});
}
function monthKey(iso){ return iso.slice(0,7); }
function monthLabel(key){
  const d = new Date(key + '-01T00:00:00');
  return d.toLocaleDateString('en-GB',{month:'short'}) + " '" + key.slice(2,4);
}
function esc(s){
  return String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
}
function toast(msg){
  const t = $('#toast');
  t.textContent = msg;
  t.classList.add('show');
  clearTimeout(t._t);
  t._t = setTimeout(()=>t.classList.remove('show'), 1700);
}
function copy(text){
  const done = () => toast('Copied  ' + text);
  if (navigator.clipboard && window.isSecureContext){
    navigator.clipboard.writeText(text).then(done).catch(()=>fallbackCopy(text,done));
  } else fallbackCopy(text, done);
}
function fallbackCopy(text, done){
  const ta = document.createElement('textarea');
  ta.value = text; ta.style.position='fixed'; ta.style.opacity='0';
  document.body.appendChild(ta); ta.select();
  try { document.execCommand('copy'); done(); } catch(e){ toast('Copy unavailable'); }
  document.body.removeChild(ta);
}

/* ============================================================
   4. FILTER + SORT
   ============================================================ */
function filtered(){
  const q = state.q.trim().toLowerCase();
  let rows = DATA.filter(r => {
    if (q && !(r.company.toLowerCase().includes(q) || (r.ticker||'').toLowerCase().includes(q))) return false;
    if (state.exchange && r.exchange !== state.exchange) return false;
    if (state.sector && r.sector !== state.sector) return false;
    if (state.status && r.status !== state.status) return false;
    if (state.month && monthKey(r.listDate) !== state.month) return false;
    if (state.watchOnly && !watch.has(r.company)) return false;
    return true;
  });
  const k = state.sort, d = state.dir;
  if (k) rows.sort((a,b) => {
    let A = a[k], B = b[k];
    if (k === 'valUsd'){
      if (!A && B) return 1;                      // unknown deal size sorts last
      if (!B && A) return -1;
      return (A - B) * d;
    }
    if (k === 'ceo' || k === 'cfo'){                 // push N/A to the bottom either way
      const an = NA(A), bn = NA(B);
      if (an && !bn) return 1;
      if (bn && !an) return -1;
    }
    return String(A).localeCompare(String(B)) * d;
  });
  return rows;
}

/* ============================================================
   5. RENDER
   ============================================================ */
function personCell(name, email, conf){
  if (NA(name)) return '<span class="na">N/A</span>';
  let out = '<div style="font-weight:500">' + esc(name) + '</div>';
  if (NA(email)){
    out += '<div class="na" style="margin-top:3px">N/A</div>';
  } else {
    out += '<div class="mail" style="margin-top:3px">'
        + '<a href="mailto:' + esc(email) + '">' + esc(email) + '</a>'
        + '<button class="icon-btn" data-copy="' + esc(email) + '" title="Copy email" aria-label="Copy ' + esc(email) + '">'
        + '<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">'
        + '<rect x="9" y="9" width="12" height="12" rx="2"/><path d="M5 15V5a2 2 0 0 1 2-2h10"/></svg></button>'
        + '<span class="flag ' + (conf === 'verified' ? 'v">verified' : 'i">inferred') + '</span></div>';
  }
  return out;
}

function drawer(r){
  return '<tr class="detail"><td colspan="9"><div class="drawer">'
    + '<div>'
      + '<p class="dl-h">Business description</p>'
      + '<p class="desc">' + esc(r.desc) + '</p>'
      + '<p class="dl-h">Transaction detail</p>'
      + '<div class="facts">'
        + fact('Exchange', r.exchange + ' — ' + (EXCHANGE_NAME[r.exchange] || r.exchange))
        + fact('Ticker', r.ticker || 'N/A')
        + fact('Expected listing', fmtDate(r.listDate))
        + fact('Timing basis', r.dateNote)
        + fact('Filing status', r.status)
        + fact('Expected valuation', r.valDisp)
        + fact('Issue price', r.pricePerShare)
        + fact('Shares offered', r.sharesOffered ? r.sharesOffered.toLocaleString('en-US') : 'N/A')
        + fact('Headquarters', r.hq)
        + fact('Bookrunners', r.bank)
      + '</div>'
    + '</div>'
    + '<div>'
      + '<p class="dl-h">Executive contacts</p>'
      + person('Chief Executive Officer', r.ceo, r.ceoEmail, r.ceoConf)
      + person('Chief Financial Officer', r.cfo, r.cfoEmail, r.cfoConf)
      + (NA(r.ir) ? '' : person('Investor relations — fallback route', 'Company IR desk', r.ir, 'inferred'))
    + '</div>'
  + '</div></td></tr>';
}
function fact(l,v){
  const empty = NA(v);
  return '<div><div class="fact-l">' + esc(l) + '</div><div class="fact-v' + (empty?' na':'') + '">' + esc(empty ? 'N/A' : v) + '</div></div>';
}
function person(role, name, email, conf){
  let out = '<div class="person"><div class="person-r">' + esc(role) + '</div>';
  if (NA(name)){
    out += '<div class="person-n na" style="font-weight:400">Not disclosed in filing</div>'
        + '<div class="na" style="font-size:11.5px">N/A</div></div>';
    return out;
  }
  out += '<div class="person-n">' + esc(name) + '</div>';
  if (NA(email)){
    out += '<div class="na" style="font-size:11.5px">N/A</div>';
  } else {
    out += '<div class="person-e"><a class="mail" href="mailto:' + esc(email) + '">' + esc(email) + '</a>'
        + '<button class="icon-btn" data-copy="' + esc(email) + '" title="Copy email" aria-label="Copy ' + esc(email) + '">'
        + '<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">'
        + '<rect x="9" y="9" width="12" height="12" rx="2"/><path d="M5 15V5a2 2 0 0 1 2-2h10"/></svg></button>'
        + '<span class="flag ' + (conf === 'verified' ? 'v">verified' : 'i">inferred') + '</span></div>';
  }
  return out + '</div>';
}

function render(){
  const rows = filtered();
  const tb = $('#tbody');
  tb.innerHTML = rows.map(r => {
    const on = state.open.has(r.company);
    const starred = watch.has(r.company);
    return '<tr class="row' + (on?' open':'') + '" data-co="' + esc(r.company) + '">'
      + '<td><button class="expand" data-toggle="' + esc(r.company) + '" aria-expanded="' + on + '" aria-label="Toggle detail for ' + esc(r.company) + '">' + (on?'&minus;':'+') + '</button></td>'
      + '<td><button class="icon-btn' + (starred?' starred':'') + '" data-star="' + esc(r.company) + '" aria-pressed="' + starred + '" aria-label="Save ' + esc(r.company) + ' to watchlist">'
        + '<svg width="13" height="13" viewBox="0 0 24 24" fill="' + (starred?'currentColor':'none') + '" stroke="currentColor" stroke-width="1.8"><path d="M12 3l2.6 5.6 6.4.8-4.7 4.3 1.3 6.3L12 17l-5.6 3 1.3-6.3L3 9.4l6.4-.8z"/></svg></button></td>'
      + '<td><div class="co">' + esc(r.company) + '</div><div class="co-sub">' + esc(r.ticker || 'N/A') + ' &middot; ' + esc(r.status) + '</div></td>'
      + '<td><div class="xchg"><i class="dot" style="background:var(--' + (REGION[r.exchange] || 'muted') + ')"></i>' + esc(r.exchange) + '</div>'
        + '<div class="co-sub" style="margin-left:14px">' + esc((EXCHANGE_NAME[r.exchange] || r.exchange)) + '</div></td>'
      + '<td><div class="date">' + fmtDate(r.listDate) + '<small>' + esc(r.dateNote) + '</small></div></td>'
      + '<td><span class="sector">' + esc(r.sector) + '</span></td>'
      + '<td><div class="num">' + esc(r.valDisp) + '</div><div class="co-sub">$' + (r.valUsd >= 1000 ? (r.valUsd/1000).toFixed(1) + 'bn' : r.valUsd + 'm') + ' equiv.</div></td>'
      + '<td>' + personCell(r.ceo, r.ceoEmail, r.ceoConf) + '</td>'
      + '<td>' + personCell(r.cfo, r.cfoEmail, r.cfoConf) + '</td>'
      + '</tr>'
      + (on ? drawer(r) : '');
  }).join('');

  $('#empty').hidden = rows.length > 0;
  $('#shown').textContent = rows.length;
  $('#total').textContent = DATA.length;
  $('#watchCount').textContent = watch.size ? '(' + watch.size + ')' : '';

  document.querySelectorAll('thead th.sortable').forEach(th => {
    const on = th.dataset.k === state.sort;
    th.classList.toggle('sorted', on);
    th.querySelector('.arrow')?.remove();
    const s = document.createElement('span');
    s.className = 'arrow';
    s.textContent = on ? (state.dir === 1 ? '▲' : '▼') : '↕';
    th.appendChild(s);
  });
}

function renderRail(){
  const keys = [...new Set(DATA.map(r => monthKey(r.listDate)))].sort();
  $('#rail').innerHTML = keys.map(k => {
    const items = DATA.filter(r => monthKey(r.listDate) === k);
    const pips = items.map(r => '<div class="pip" style="background:var(--' + (REGION[r.exchange] || 'muted') + ')" title="' + esc(r.company) + '"></div>').join('');
    return '<button class="bucket' + (state.month === k ? ' on' : '') + '" data-month="' + k + '" '
      + 'aria-pressed="' + (state.month === k) + '" title="' + items.length + ' listing(s) in ' + monthLabel(k) + '">'
      + '<div class="bucket-stack">' + pips + '</div>'
      + '<div class="bucket-l">' + monthLabel(k) + ' · ' + items.length + '</div></button>';
  }).join('');
}

function renderStats(){
  $('#statCos').textContent = DATA.length;
  $('#statXch').textContent = new Set(DATA.map(r => r.exchange)).size;
  const total = DATA.reduce((s,r) => s + r.valUsd, 0);
  $('#statVal').textContent = '$' + (total/1000).toFixed(0) + 'bn';
  const filed = DATA.filter(r => r.status === 'Filed' || r.status === 'Approved').length;
  $('#statFiled').textContent = filed + ' / ' + DATA.length;
}

function renderControls(){
  const xs = [...new Set(DATA.map(r => r.exchange))].sort();
  $('#xchg').innerHTML = '<option value="">All exchanges</option>'
    + xs.map(x => '<option value="' + x + '">' + x + ' — ' + (EXCHANGE_NAME[x] || x)
        + (LIVE_EXCHANGES.has(x) ? ' (live)' : CURATED_NOTES.has(x) ? ' (needs subscription)' : '') + '</option>').join('');
  const ss = [...new Set(DATA.map(r => r.sector))].sort();
  $('#sectors').innerHTML = '<button class="chip' + (state.sector===''?' on':'') + '" data-sector="">All sectors</button>'
    + ss.map(s => '<button class="chip" data-sector="' + esc(s) + '">' + esc(s) + '</button>').join('');
}

/* ============================================================
   6. CSV EXPORT
   ============================================================ */
function exportCsv(){
  const rows = filtered();
  if (!rows.length) return toast('Nothing to export');
  const head = ['Company','Ticker','Exchange','Exchange City','Expected Listing Date','Timing Basis','Sector',
                'Filing Status','Expected Valuation','USD Equivalent (m)','Issue Price','Shares Offered','CEO','CEO Email','CEO Email Confidence',
                'CFO','CFO Email','CFO Email Confidence','Headquarters','Bookrunners','Business Description'];
  const cell = v => '"' + String(v ?? 'N/A').replace(/"/g,'""') + '"';
  const body = rows.map(r => [
    r.company, r.ticker || 'N/A', r.exchange, EXCHANGE_NAME[r.exchange] || r.exchange, r.listDate, r.dateNote, r.sector,
    r.status, r.valDisp, r.valUsd, r.pricePerShare || 'N/A', r.sharesOffered || 'N/A', r.ceo, r.ceoEmail, r.ceoConf || 'N/A',
    r.cfo, r.cfoEmail, r.cfoConf || 'N/A', r.hq, r.bank, r.desc
  ].map(cell).join(','));
  const csv = [head.map(cell).join(','), ...body].join('\r\n');
  const url = URL.createObjectURL(new Blob(['\ufeff' + csv], {type:'text/csv;charset=utf-8;'}));
  const a = document.createElement('a');
  a.href = url;
  a.download = 'ipo-tracker-' + new Date().toISOString().slice(0,10) + '.csv';
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  URL.revokeObjectURL(url);
  toast('Exported ' + rows.length + ' listings');
}

/* ============================================================
   7. EVENTS
   ============================================================ */
$('#q').addEventListener('input', e => { state.q = e.target.value; render(); });
$('#xchg').addEventListener('change', e => { state.exchange = e.target.value; render(); });
$('#status').addEventListener('change', e => { state.status = e.target.value; render(); });
$('#csvBtn').addEventListener('click', exportCsv);
$('#clearBtn').addEventListener('click', clearAll);

$('#watchBtn').addEventListener('click', e => {
  state.watchOnly = !state.watchOnly;
  e.currentTarget.classList.toggle('on', state.watchOnly);
  e.currentTarget.setAttribute('aria-pressed', state.watchOnly);
  render();
});

$('#sectors').addEventListener('click', e => {
  const b = e.target.closest('[data-sector]');
  if (!b) return;
  state.sector = b.dataset.sector;
  document.querySelectorAll('#sectors .chip').forEach(c => c.classList.toggle('on', c === b));
  render();
});

$('#rail').addEventListener('click', e => {
  const b = e.target.closest('[data-month]');
  if (!b) return;
  state.month = (state.month === b.dataset.month) ? '' : b.dataset.month;
  renderRail(); render();
});

document.querySelector('thead').addEventListener('click', e => {
  const th = e.target.closest('th.sortable');
  if (!th) return;
  const k = th.dataset.k;
  if (state.sort !== k) { state.sort = k; state.dir = 1; }        // new column: ascending
  else if (state.dir === 1) state.dir = -1;                       // 2nd click: descending
  else state.sort = null;                                          // 3rd click: back to unsorted
  render();
});
document.querySelectorAll('thead th.sortable').forEach(th => {
  th.tabIndex = 0;
  th.addEventListener('keydown', e => {
    if (e.key === 'Enter' || e.key === ' '){ e.preventDefault(); th.click(); }
  });
});

$('#tbody').addEventListener('click', e => {
  const t = e.target.closest('[data-toggle]');
  if (t){
    const co = t.dataset.toggle;
    state.open.has(co) ? state.open.delete(co) : state.open.add(co);
    return render();
  }
  const s = e.target.closest('[data-star]');
  if (s){
    const co = s.dataset.star;
    watch.has(co) ? watch.delete(co) : watch.add(co);
    store.set('ipo.watchlist', JSON.stringify([...watch]));
    toast(watch.has(co) ? 'Saved to watchlist' : 'Removed from watchlist');
    return render();
  }
  const c = e.target.closest('[data-copy]');
  if (c) copy(c.dataset.copy);
});

function clearAll(){
  state.q = ''; state.exchange = ''; state.sector = ''; state.status = '';
  state.month = ''; state.watchOnly = false; state.sort = null; state.dir = 1;
  $('#q').value = ''; $('#xchg').value = ''; $('#status').value = '';
  $('#watchBtn').classList.remove('on');
  $('#watchBtn').setAttribute('aria-pressed','false');
  document.querySelectorAll('#sectors .chip').forEach((c,i) => c.classList.toggle('on', i === 0));
  renderRail(); render();
}

/* ============================================================
   BOOT
   ============================================================ */
document.getElementById('refreshBtn')?.addEventListener('click', () => refresh(false));

(async () => {
  await loadData(false);
  renderStats();
  renderControls();
  renderRail();
  render();
  stampSync();
  if (location.protocol !== 'file:'){
    setInterval(() => refresh(true), REFRESH_MS);
    document.addEventListener('visibilitychange', () => {
      if (!document.hidden) refresh(true);       // catch up after a backgrounded tab
    });
  }
})();
